/* Writing Prompt Generator — prompt bank.
   Organized by grade band (ms/hs) then genre. 20 prompts per genre per band
   (5 genres x 2 bands x 20 = 200 total), written distinctly for each band
   rather than reusing the same prompts with a relabel. */
(function (global) {
  'use strict';

  var GENRES = [
    { key: 'narrative', label: 'Narrative' },
    { key: 'persuasive', label: 'Persuasive / Argumentative' },
    { key: 'descriptive', label: 'Descriptive' },
    { key: 'expository', label: 'Expository / Informative' },
    { key: 'creative', label: 'Creative / Fiction' }
  ];

  var PROMPTS = {
    ms: {
      narrative: [
        "Write about a time you tried something new and it didn't go as planned.",
        "Tell the story of the best day you've had this year.",
        "Write about a time you had to stand up for yourself or someone else.",
        "Describe a moment when you were really scared, and how you got through it.",
        "Write about a time you got in trouble and what you learned from it.",
        "Tell the story of a friendship that changed over time.",
        "Write about the first time you tried a new food, sport, or activity.",
        "Describe a time when you helped someone without being asked.",
        "Write about a memorable trip or vacation you took.",
        "Tell the story of a time you had to solve a problem on your own.",
        "Write about a time you disagreed with a friend and how you worked it out.",
        "Describe a moment when you felt really proud of yourself.",
        "Write about a time an adult surprised you by being wrong, or right, about something.",
        "Tell the story of your most embarrassing moment, and why it's actually funny now.",
        "Write about a pet or animal that means a lot to you.",
        "Describe a time you had to wait for something you really wanted.",
        "Write about a time you moved, changed schools, or met someone new.",
        "Tell the story of a family tradition and why it matters to you.",
        "Write about a time you failed at something before you finally succeeded.",
        "Describe the moment you realized you were growing up."
      ],
      persuasive: [
        "Should students get to choose their own seats in class? Convince your teacher.",
        "Argue for or against year-round school schedules.",
        "Should homework be optional? Take a side and defend it.",
        "Convince your parents to let you get a pet.",
        "Should cell phones be allowed in middle school? Argue your position.",
        "Should students have a say in what's served in the cafeteria?",
        "Argue for or against school uniforms.",
        "Should grades be replaced with pass/fail for every class?",
        "Convince your school to add a new club or elective.",
        "Should students be allowed to listen to music while doing classwork?",
        "Argue whether recess should be required for every grade level.",
        "Should video games count as a sport?",
        "Convince someone that your favorite book or movie is worth their time.",
        "Should the school day start later in the morning?",
        "Argue for or against a longer summer break.",
        "Should students be able to retake tests to improve their grade?",
        "Convince your classmates to try a new hobby you love.",
        "Should kids your age be allowed to have social media accounts?",
        "Argue whether it's better to have a big group of friends or a few close ones.",
        "Should students be assigned seats on the bus?"
      ],
      descriptive: [
        "Describe your favorite place in as much detail as possible.",
        "Describe a storm from the point of view of someone watching from a window.",
        "Describe your bedroom in a way that shows something about your personality.",
        "Describe the sights, sounds, and smells of your favorite meal.",
        "Describe a person you admire without saying their name — let details reveal who they are.",
        "Describe the school cafeteria at the busiest moment of lunch.",
        "Describe walking into your house after a really long day.",
        "Describe what it feels like to ride your favorite amusement park ride.",
        "Describe the inside of a locker, backpack, or desk that says a lot about its owner.",
        "Describe the last five minutes before the school day ends.",
        "Describe your neighborhood as if you were seeing it for the first time.",
        "Describe a season changing where you live.",
        "Describe the feeling of finally finishing something you worked hard on.",
        "Describe an object that has been in your family for a long time.",
        "Describe what your town looks like from the highest point around.",
        "Describe the moment right before you fall asleep.",
        "Describe a place that feels completely different at night than during the day.",
        "Describe the chaos, or calm, of a family gathering.",
        "Describe your favorite outdoor spot in every season.",
        "Describe what silence sounds like."
      ],
      expository: [
        "Explain how to do something you're really good at.",
        "Explain the rules of your favorite game or sport to someone who's never played.",
        "Explain why a historical event you've studied still matters today.",
        "Explain how something you use every day actually works.",
        "Explain the steps to plan the perfect birthday party.",
        "Explain why your favorite subject in school is worth studying.",
        "Explain the causes and effects of a problem in your community.",
        "Explain how to be a good teammate or group member.",
        "Explain the process of how your favorite food is made.",
        "Explain what makes a good leader, using examples.",
        "Explain how social media has changed how kids your age communicate.",
        "Explain the difference between two things people often confuse.",
        "Explain what a typical day looks like for you, and why it works, or doesn't.",
        "Explain how to train a pet to do a trick.",
        "Explain why recycling or reducing waste matters.",
        "Explain how weather forecasting works, based on what you know.",
        "Explain the unwritten rules of your friend group or grade.",
        "Explain how a book or movie changed the way you think about something.",
        "Explain how to stay motivated when something is hard.",
        "Explain what you wish more adults understood about being a kid today."
      ],
      creative: [
        "Write a story that begins: The last thing I expected to find in my locker was...",
        "You wake up and gravity works sideways for one day. Write about it.",
        "Write a story from the point of view of the family pet.",
        "Invent a new holiday and write the story of how it started.",
        "Write a story where the main character can hear other people's thoughts for one hour.",
        "You find a door in your school that's never been there before. Where does it lead?",
        "Write a story that takes place entirely inside a video game.",
        "A character discovers they can talk to animals — but only ones they've been mean to.",
        "Write about a kid who trades places with their teacher for a day.",
        "Your character opens a fortune cookie and the fortune actually starts coming true.",
        "Write a story where the school library is secretly magical.",
        "A character finds an old photograph of themselves, from 100 years ago.",
        "Write about the day the internet disappeared forever.",
        "Your character wakes up as the youngest sibling instead of the oldest, or the other way around.",
        "Write a story where every lie a character tells becomes real.",
        "A mysterious package arrives with no return address. What's inside?",
        "Write about a world where kids run everything and adults have to ask permission.",
        "Your character finds a map that leads somewhere in your own town.",
        "Write a story that starts in the middle of an argument, and explain what led there.",
        "A character's shadow starts acting on its own."
      ]
    },
    hs: {
      narrative: [
        "Write about a moment that changed how you see yourself.",
        "Describe an experience that forced you to reconsider a belief you'd always held.",
        "Write about a time you had to make a decision with no clearly right answer.",
        "Tell the story of a relationship that taught you something about yourself.",
        "Write about a time you felt like an outsider, and how you responded.",
        "Describe a moment when you disappointed someone you respect, and what happened next.",
        "Write about an experience that made you more aware of privilege, yours or someone else's.",
        "Tell the story of the first time you truly failed at something that mattered to you.",
        "Write about a time you had to choose between loyalty to a group and your own values.",
        "Describe a moment that made you question what growing up really means.",
        "Write about an experience with a person from a different generation that surprised you.",
        "Tell the story of a time silence said more than words could have.",
        "Write about a moment you realized your parents, or another adult, were just people, not authorities.",
        "Describe an experience that changed your relationship with your community or culture.",
        "Write about a time you had to apologize for something you didn't think was wrong.",
        "Tell the story of an experience that shaped your understanding of fairness.",
        "Write about a time you had to let go of something, or someone, important.",
        "Describe an experience navigating two different versions of yourself — at home vs. school, online vs. in person.",
        "Write about a risk you took that didn't pay off, and what it taught you anyway.",
        "Tell the story of the moment you started to figure out who you want to be."
      ],
      persuasive: [
        "Should social media platforms be held legally responsible for content posted by users?",
        "Argue for or against the use of artificial intelligence in schoolwork.",
        "Should voting be mandatory for all eligible citizens?",
        "Take a position: does standardized testing accurately measure student ability?",
        "Should college be free for all students, funded by taxes?",
        "Argue whether social media has done more good or harm to teenagers.",
        "Should the driving age be raised or lowered?",
        "Take a position on whether zoos and aquariums are ethical.",
        "Should students be required to complete community service to graduate?",
        "Argue for or against censoring books in school libraries.",
        "Should employers be allowed to require drug testing for all applicants?",
        "Take a position: is it ethical to eat meat, given current farming practices?",
        "Should the government regulate how apps are designed to be addictive?",
        "Argue whether history classes should focus more on uncomfortable truths than national pride.",
        "Should professional athletes be paid more than teachers, doctors, or scientists?",
        "Take a position on whether the death penalty should be abolished.",
        "Should schools eliminate homework entirely in favor of in-class work?",
        "Argue for or against requiring national service, military or civilian, after high school.",
        "Should companies be allowed to use customer data to target advertising to minors?",
        "Take a position: should there be a maximum wage as well as a minimum wage?"
      ],
      descriptive: [
        "Describe a place that no longer exists except in memory.",
        "Describe the exact moment a relationship began to change, without naming the emotion directly.",
        "Describe a person through the objects they leave behind in a room.",
        "Describe the atmosphere of a place during a moment of collective tension — a waiting room, a courtroom, a locker room before a big game.",
        "Describe your hometown the way a stranger would see it for the first time.",
        "Describe the physical sensation of a strong emotion without naming the emotion.",
        "Describe a photograph that captures more than what's visible in it.",
        "Describe the last conversation you remember clearly with someone who's no longer in your life.",
        "Describe an ordinary object as if it were a museum artifact from the future.",
        "Describe the difference between how a place looks in daylight versus at night.",
        "Describe a crowd of people as if they were a single organism.",
        "Describe the inside of your own mind during a moment of decision.",
        "Describe a meal that meant more than food.",
        "Describe a building or space that reflects the values of the people who use it.",
        "Describe silence in a moment when you expected noise.",
        "Describe the weather as a metaphor for something happening in your life.",
        "Describe a stranger you observed closely enough to imagine their whole life.",
        "Describe the exact texture, weight, and feel of an object tied to a specific memory.",
        "Describe a version of your city or town fifty years from now.",
        "Describe the sound of a place you know well with your eyes closed."
      ],
      expository: [
        "Explain how a specific piece of legislation or court decision changed everyday life.",
        "Explain the economic forces behind a current event in the news.",
        "Explain how propaganda techniques are used in modern advertising.",
        "Explain the scientific process behind a phenomenon you find fascinating.",
        "Explain how a historical event's causes are still debated by historians today.",
        "Explain the process of how a bill becomes law, and where it commonly gets stuck.",
        "Explain how confirmation bias affects the way people consume news.",
        "Explain the environmental and economic tradeoffs of a specific energy source.",
        "Explain how a piece of technology you use every day has changed society.",
        "Explain the psychological principles behind why people conform to group behavior.",
        "Explain how a specific culture's traditions reflect its history or geography.",
        "Explain the arguments on multiple sides of a current policy debate, fairly.",
        "Explain how algorithms shape what information people see online.",
        "Explain the process and ethics of a scientific breakthrough, such as gene editing or AI.",
        "Explain how a historical figure's reputation has changed over time, and why.",
        "Explain the systemic factors that contribute to a social issue you care about.",
        "Explain how a specific work of literature reflects the era it was written in.",
        "Explain the mechanics of how misinformation spreads online.",
        "Explain the tradeoffs between individual freedom and collective safety, using a real example.",
        "Explain how a specific industry has been transformed by automation."
      ],
      creative: [
        "Write a story told entirely through text messages or emails.",
        "Write about a character who discovers the world they know is a simulation.",
        "Write a story set in a future where privacy no longer exists.",
        "A character finds a letter written by themselves, ten years in the future.",
        "Write a story where the antagonist believes they are the hero.",
        "Write about a society where emotions are regulated by law.",
        "A character can relive one day of their life, but changes something small each time.",
        "Write a story that takes place during the last hour before a major historical event.",
        "Write about two characters on opposite sides of a conflict who discover common ground.",
        "A character wakes up with no memory of the last ten years. Write what they piece together.",
        "Write a story where technology designed to help people ends up controlling them.",
        "Write about a character forced to choose between truth and loyalty.",
        "Write a story set entirely in a single elevator, car, or waiting room.",
        "A character discovers a hidden talent for lying, and it saves someone's life.",
        "Write about a world where everyone can see how much time they have left.",
        "Write a story that reveals its twist only in the final line.",
        "A character returns to their hometown after years away, and nothing is as they remembered.",
        "Write about an AI character grappling with whether it has free will.",
        "Write a story where the setting is itself a kind of character.",
        "Write about the last person on Earth to remember something everyone else has forgotten."
      ]
    }
  };

  global.WritingPrompts = { GENRES: GENRES, PROMPTS: PROMPTS };
})(typeof window !== 'undefined' ? window : global);
